### PR TITLE
Rewrite RHODS listing

### PR DESCRIPTION
**Pull request by zdtsw**
ref: https://github.com/opendatahub-io/opendatahub-community/issues/98

changes only apply to RHODS

we will still need to update midstream CSV (once this PR is merged) to get it out in 1.33

### CODE REVIEW

**Comment by erwangranger** [comment]
Hello, 

I am not sure this is the right place to make the update we want. 
Our goal is to update the text displayed in OperatorHub for RHODS, which looks like the following:
image
The text this PR is updating does not match with the text in the screenshot above.

**Comment by zdtsw** [comment]
this PR is only for the v2 operator.
will have another one for the v1 operator if above screenshot looks good

**Comment by erwangranger** [comment]
Yes, the screenshot looks good.

**Comment by VaishnaviHire** [comment]
@zdtsw This change looks good, we also need to update bundle in `main` branch to match [release branches](https://github.com/red-hat-data-services/rhods-operator/blob/rhods-1.32/bundle/manifests/rhods-operator.clusterserviceversion.yaml#L224), but that can be done in follow up PR.

Note this needs to also be reflected in midstream CSV

**Comment by zdtsw** [comment]
> @zdtsw This change looks good, we also need to update bundle in `main` branch to match [release branches](https://github.com/red-hat-data-services/rhods-operator/blob/rhods-1.32/bundle/manifests/rhods-operator.clusterserviceversion.yaml#L224), but that can be done in follow up PR.
> 
> Note this needs to also be reflected in midstream CSV

Thought we do not need it to be in 1.32, otherwise we will need another RC rebuild?
if this can be wait for 1.33, we can get release branch off main after next week.

Yes for midstream PR is created https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1041

**Comment by VaishnaviHire** [comment]
Also note, for this update to be reflected in default channel, we would need to update csv of v1.x operator

**Comment by zdtsw** [comment]
> Also note, for this update to be reflected in default channel, we would need to update csv of v1.x operator

yep, midstream PR includes both v1 and v2 operator changes

**Comment by zdtsw** [comment]
change in midstream has been  merged into 1.33 nightly

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
