### PR TITLE
[sync]: refactor(webhook): change for mutating webhook to use Default to set ModelReg namespace

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

- re-generate bundles with controller 0.16.1 (seems we got it reverted in https://github.com/red-hat-data-services/rhods-operator/pull/355)
- also cherry-pick https://github.com/opendatahub-io/opendatahub-operator/pull/1241
- add missing changes for keywords in config

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dhirajsb** [comment]
@zdtsw model registry team were not informed of this decision. 
@rareddy were you aware that this was being defaulted to `odh-model-registries` for rhoai?

**Comment by zdtsw** [comment]
> @zdtsw model registry team were not informed of this decision. @rareddy were you aware that this was being defaulted to `odh-model-registries` for rhoai?

to be clear, the change is only for the API, not for the release.
for downstream build, the default one which auto installed by operator is rhoai-model-registries, not odh-model-registries.

**Comment by rareddy** [comment]
Is there any underlying reason to keep the same name between ODH and RHOAI?

@dhirajsb is this going to affect any of the processes or functionality in downstream (i.e. testing, docs etc)

**Comment by rareddy** [comment]
@zdtsw so, the user now needs to explicitly select ` rhoai-model-registries` DSC CR in RHOAI if they want to put model registries other than `odh-model-registries` which will be default in both ODH and RHOAI.

**Comment by zdtsw** [comment]
> @zdtsw so, the user now needs to explicitly select ` rhoai-model-registries` DSC CR in RHOAI if they want to put model registries other than `odh-model-registries` which will be default in both ODH and RHOAI.

there are basically 2 ways for user to use modelreg with RHOAI:
- install it from OperatorHub UI:  they see this as pre-filled values on clean installation
Screenshot from 2024-10-01 09-25-09
- GitOps fashion to create DSC CR: 
```
   .....
  modelregistry:
      managementState: Removed
      registriesNamespace: <their choice of namespace>
   .....
```
they can put any value for registriesNamespace during this step.  => if they use `odh-model-registries` for RHOAI release, we do not block that as well. 
only if they do
 

```
   .....
  modelregistry:
      managementState: Removed
   .....
```

this will be equal to 
 
```
   .....
  modelregistry:
      managementState: Removed
      registriesNamespace: odh-model-registries
   .....
```

**Comment by rareddy** [comment]
@zdtsw Thank you for the explanation, that is very clear. The only corner case I see is, since MR is in tech preview most of the installs start with 

```.....
  modelregistry:
      managementState: Removed
   .....
```
then once in the future when MR goes to GA as part of an upgrade or manual enablement, since the `registriesNamespace` is set to be immutable, the user can not change it in an existing installation and thus will leave with a mixed namespace of installs.

**Comment by zdtsw** [comment]
> @zdtsw Thank you for the explanation, that is very clear. The only corner case I see is, since MR is in tech preview most of the installs start with
> 
> ```
>   modelregistry:
>       managementState: Removed
>    .....
> ```
> 
> then once in the future when MR goes to GA as part of an upgrade or manual enablement, since the `registriesNamespace` is set to be immutable, the user can not change it in an existing installation and thus will leave with a mixed namespace of installs.


when ModelReg gets GA, 
- from UI, clean installation will get
```
 .....
  modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
   .....
```
- from CLI, they should set  this to create DSC CR  ======> i think "docs" should have somethng in releasenotes, even in 2.14 , right? 
 ```
 .....
  modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
   .....
```
- from CLI, if they try with   =======================> refer to the same docs ^ 
```
 .....
  modelregistry:
      managementState: Managed
   .....
```
then they get 
 ```
 .....
  modelregistry:
      managementState: Managed
      registriesNamespace: odh-model-registries   =================> this is not wrong still, since we support non "rhoai-model-registries" as well
   .....
```

As for someone already has ModelReg in DSC CR, with upgrade, we wont overwrite the status from Removed to Managed even for the GA, e.g
 ```
 .....
modelregistry:
      managementState: Removed
   .....
 ```
will be kept the same Removed
so they can turn it on by
chaning  managementState: Managed and set any namespace they would like to use for registriesNamespace; or skip set registriesNamespace then get odh-model-registries

**Comment by rareddy** [comment]
>will be kept the same Removed
so they can turn it on by
chaning to managementState: Managed and set any namespace they would like to use for registriesNamespace; or skip set registriesNamespace then get odh-model-registries

So are you saying that the user is allowed to change `registriesNamespace` when they flip the `managementState: Removed` to `managementState: Managed` the very first time. If they do not enter  `registriesNamespace` then they get the default `odh-model-registries`. That is good. Thanks.

**Comment by zdtsw** [comment]
> > will be kept the same Removed
> > so they can turn it on by
> > chaning to managementState: Managed and set any namespace they would like to use for registriesNamespace; or skip set registriesNamespace then get odh-model-registries
> 
> So are you saying that the user is allowed to change `registriesNamespace` when they flip the `managementState: Removed` to `managementState: Managed` the very first time. If they do not enter `registriesNamespace` then they get the default `odh-model-registries`. That is good. Thanks.

so the logic in the current code (regardless with or without this PR) is user can change `registriesNamespace` to any value back and forth, as long as the old status has `managementState: Removed`  ahdn this will not creat namespace in the cluster. 
Till the first time `managementState: Managed` is set and the namespace will be created with the value from `registriesNamespace` and after that, user cannot change `registriesNamespace` again.  Till they set  `managementState: Removed` again.

**Comment by VaishnaviHire** [comment]
@lburgazzoli Can you also take a look at this change? Afaik, we should be able to get updated defaults in CRDs. Also we do not support installation of ODH and RHOAI in one cluster.

**Comment by zdtsw** [comment]
after some offline discussion, will keep rhoai-model-registries as the default namespace value in CRD, i will revert change on that part

**Pull request merged**
