### PR TITLE
update: make TrustyAI GA

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Test failure in trusty ai probably because `get_all_manifests` do not point to `main`?

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
> /test rhods-operator-e2e

could be something from the e2e tests, if that is verified working by QE

**Comment by zdtsw** [comment]
seems it is fine with e2e

**Review by zdtsw — APPROVED** [review]

**Pull request merged**
