### PR TITLE
Init: import from ODH rhoai branch for RHOAI 2.16

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

this is basically a snapshot from https://github.com/opendatahub-io/opendatahub-operator/commit/a9422e85bcc14a697c8d53ea0e633a2719f98070

https://issues.redhat.com/browse/RHOAIENG-14120

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
from pod log, that looks like is running with the old rhods-operator binary 🤔

**Comment by VaishnaviHire** [comment]
@zdtsw We need to revert the image change https://github.com/red-hat-data-services/rhods-operator/pull/552/files#diff-8ec76fb27d43278dfd517742bfaedb5c3b57ff3f64965cb6a97c35266316878eR1176

**Comment by zdtsw** [comment]
> @zdtsw We need to revert the image change https://github.com/red-hat-data-services/rhods-operator/pull/552/files#diff-8ec76fb27d43278dfd517742bfaedb5c3b57ff3f64965cb6a97c35266316878eR1176

good findings! 👍

**Comment by zdtsw** [comment]
:man_dancing:

**Pull request merged**
