### PR TITLE
[sync]: chore changes from ODH to rhoai main

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

ODH:
e80dcbe8b28d5dcc77284498466055532a20b80c https://github.com/opendatahub-io/opendatahub-operator/pull/1144
a890ffa6b32e5ec3e2c1e458adcfcab44b03e8ca https://github.com/opendatahub-io/opendatahub-operator/pull/1148
31185c3515631970723a340dab91265ca4aca53a https://github.com/opendatahub-io/opendatahub-operator/pull/1149

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
You use `git cherry-pick` for that, don't you?
Can you use the option:
```
       -x
           When recording the commit, append a line that says "(cherry picked from commit ...)" to the original commit message in order to indicate which commit this
           change was cherry-picked from. This is done only for cherry picks without conflicts. Do not use this option if you are cherry-picking from your private
           branch because the information is useless to the recipient. If on the other hand you are cherry-picking between two publicly visible branches (e.g.
           backporting a fix to a maintenance branch for an older release from a development branch), adding this information can be useful.
```

The scenario is almost ours. It allows:
1) easier tracking what changes were backported
2) compare original and ported patch just looking into git log of the PR without extra lookup via github. Really simplifies the review.

**Comment by zdtsw** [comment]
> You use `git cherry-pick` for that, don't you? Can you use the option:
> 
> ```
>        -x
>            When recording the commit, append a line that says "(cherry picked from commit ...)" to the original commit message in order to indicate which commit this
>            change was cherry-picked from. This is done only for cherry picks without conflicts. Do not use this option if you are cherry-picking from your private
>            branch because the information is useless to the recipient. If on the other hand you are cherry-picking between two publicly visible branches (e.g.
>            backporting a fix to a maintenance branch for an older release from a development branch), adding this information can be useful.
> ```
> 
> The scenario is almost ours. It allows:
> 
> 1. easier tracking what changes were backported
> 2. compare original and ported patch just looking into git log of the PR without extra lookup via github. Really simplifies the review.

good to know this "-x"

**Comment by ykaliuta** [comment]
Is d3cec13d34b8 ("(chore)Fix the token expiry and move release version update code to a composite action (#1132)") relevant for RHOAI?

**Comment by zdtsw** [comment]
> Is [d3cec13](https://github.com/red-hat-data-services/rhods-operator/commit/d3cec13d34b8af58fcf5156ce17fb698be78bfc9) ("(chore)Fix the token expiry and move release version update code to a composite action ([opendatahub-io#1132](https://github.com/opendatahub-io/opendatahub-operator/pull/1132))") relevant for RHOAI?

I see your point now, the original GH action part is not even brought down here. 
i will revert this one.

**Review by ykaliuta — APPROVED** [review]

**Pull request merged**
