### PR TITLE
fix: add missing rbac rule to scrape metrics endpoints protected by rbac, fixes RHOAIENG-13957

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description

Add missing rbac rule to scrape metrics endpoints protected by rbac
See [RHOAIENG-13957](https://issues.redhat.com/browse/RHOAIENG-13957) for more details. 

## How Has This Been Tested?

Tested by adding this rule to the prometheus-scraper role manually in a test QE cluster. 

## Merge criteria

- [X] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [X] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [X] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]

**Review by asanzgom — APPROVED** [review]

**Comment by dhirajsb** [comment]
@zdtsw @VaishnaviHire e2e keeps failing in an unrelated ray component.  Any ideas?

**Comment by dhirajsb** [comment]
@zdtsw @VaishnaviHire it's still failing for errors in other components. Please merge it manually.

**Pull request merged**
