### PR TITLE
Sync from odh for RHOAI 2.12

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Description
This PR includes all the upstream changes during 2.12 sprint. 

## JIRA issue:
- https://issues.redhat.com/browse/RHOAIENG-6295
- https://issues.redhat.com/browse/RHOAIENG-8995
- https://issues.redhat.com/browse/RHOAIENG-8540
- https://issues.redhat.com/browse/RHOAIENG-8510
- https://issues.redhat.com/browse/RHOAIENG-9326
- https://issues.redhat.com/browse/RHOAIENG-8483
- https://issues.redhat.com/browse/RHOAIENG-4233
- https://issues.redhat.com/browse/RHOAIENG-9431
- https://issues.redhat.com/browse/RHOAIENG-10268
- https://issues.redhat.com/browse/RHOAIENG-9751
- https://issues.redhat.com/browse/RHOAIENG-7297
- https://issues.redhat.com/browse/RHOAIENG-165

Note: Commits that include refactor do not have jiras in this sprint

## Merge criteria:

- [ ] Have a meaningful commit messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by mattmahoneyrh — APPROVED** [review]

**Comment by VaishnaviHire** [comment]
Tested upgrade from 2.11

**Comment by mattmahoneyrh** [comment]
lgtm

**Pull request merged**
