### PR TITLE
[sync]: Addding kfto component to odh operator

### PR DESCRIPTION
**Pull request by zdtsw**
ref:  https://issues.redhat.com/browse/RHOAIENG-4663
ref: https://issues.redhat.com/browse/RHOAIENG-5442

### CODE REVIEW

**Comment by riprasad** [comment]
@zdtsw @VaishnaviHire It's been a while. Can we merge this???

This is blocking the [midstream PR](https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1981) from getting merged

**Comment by zdtsw** [comment]
> @zdtsw @VaishnaviHire It's been a while. Can we merge this???
> 
> This is blocking the [midstream PR](https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1981) from getting merged

we are still waiting DW team for the prometheus rules

**Comment by dimakis** [comment]
@zdtsw we're working on the prom rules, but are they actually necessary? the KTO will be LA for WX.ai consumption only. is that supported by our SRE?

**Review by VaishnaviHire — APPROVED** [review]

**Comment by VaishnaviHire** [comment]
Since Wen is not here, opened a duplicate PR https://github.com/red-hat-data-services/rhods-operator/pull/266

**Pull request closed without merging**
