### PR TITLE
[sync]: code from ODH incubation to RHOAI main

### PR DESCRIPTION
**Pull request by zdtsw**

### CODE REVIEW

**Comment by zdtsw** [comment]
@ykaliuta this is only for a sanity check, not intended for full code review.

**Comment by ykaliuta** [comment]
Can we remove squashing policy for this repo? The PR were already squashed in upstream.

**Comment by zdtsw** [comment]
> Can we remove squashing policy for this repo? The PR were already squashed in upstream.

i am open to do this change, but try to understand the reason behind it (multiple commits than one final squash)

if we want to be able to better track the changes introduced in rhoai, we have the commits in the list so we can go back to see what the original change from ODH is for , right? example (https://github.com/red-hat-data-services/rhods-operator/pull/274) shows 4 commits from ODH

these cherry-pick are not 100% the same between ODH commits to the commits into this PR.
it involves resolved conflicts on every commit, therefore if anything is wrong for the "final big sync PR" it could be 
1) manual error when doing cherry-pick with resolve 2) original ODH PR is wrong

**Comment by ykaliuta** [comment]
> these cherry-pick are not 100% the same between ODH commits to the commits into this PR.

Isn't it easier to track on per-commit basis? You have original commit in ODH, you have amended commit in RHOAI. You can easily get the amendments just comparing the diffs instead of fetching them from the huge commit.

It is also good to have the list of amendments in the commit message to understand the intentions.

**Comment by zdtsw** [comment]
> > these cherry-pick are not 100% the same between ODH commits to the commits into this PR.
> 
> Isn't it easier to track on per-commit basis? You have original commit in ODH, you have amended commit in RHOAI. You can easily get the amendments just comparing the diffs instead of fetching them from the huge commit.
> 
> It is also good to have the list of amendments in the commit message to understand the intentions.

in theory, yes, if it is a 1 ODH commit :1 RHOAI commit mapping in order. 
but we do not cherry-pick on that order. e.g some old commits are not synced down (could be a human mistake mostly , could also be features that cannot add to rhoai yet)  
we will need to run test and ensure every commits  in this PR are working before starting cherry-pick the next one. 
then it is an extra efforts for the one who is doing sync on behalf of the team. 
one bad example, if commit A is not working after sync from ODH to RHOAI, because of some missing functions in that commit then we can only fix it in the later commit X, and this would not help when compare commit A from RHOAI and commit A from ODH.

we can have another discussion in the team, and identify work process. 
one thing i can think of is the one make the change in ODH should be responsible for the change land in RHOAI main.
but i am open for more options.

**Comment by zdtsw** [comment]
close this PR in favor of https://github.com/red-hat-data-services/rhods-operator/pull/287

but we can keep discussion how such [sync] should be done till we have the feature "keep odh only" done

**Pull request closed without merging**
