### PR TITLE
fix: upgrade go version from 1.20 to 1.21

### PR DESCRIPTION
**Pull request by zdtsw**
Many thanks for submitting your Pull Request ❤️!

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md)
- [ ] Pull Request contains description of the issue
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request

## JIRA issue:

ref: https://issues.redhat.com/browse/RHOAIENG-8608 

## Merge criteria:

- [ ] Have a meaningful commit messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
/hold

Do we not need Dockerfile changes for this?

**Comment by zdtsw** [comment]
> /hold
> 
> Do we not need Dockerfile changes for this?



> /hold
> 
> Do we not need Dockerfile changes for this?

good catch!
updated

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
