### PR TITLE
[sync] chore: rename variable/function name

### PR DESCRIPTION
**Pull request by zdtsw**
sync from ODH https://github.com/opendatahub-io/opendatahub-operator/pull/1147
commit https://github.com/opendatahub-io/opendatahub-operator/commit/8d5b7a485fd4d4394aa948574a7e57e1e13e817e

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by ajaypratap003 — COMMENTED** [review]
LGTM

**Comment by ykaliuta** [comment]
Could you put upstream patch reference in the commit message?

**Review by ykaliuta — APPROVED** [review]

**Pull request merged**
