### PR TITLE
fix: workbench deployment + change path for its manifests in build

### PR DESCRIPTION
**Pull request by zdtsw**
## Description

- sync to changes in ODH on workbench: to fix the problem of we did not apply correct workbench image before params.env gets updated
- also uplift branch to 2.13 to get new manifests
- refer to https://github.com/opendatahub-io/opendatahub-operator/pull/1226 but since it has the path change, cannot just sync from ODH to rhoai

ref: https://issues.redhat.com/browse/RHOAIENG-12732

## How Has This Been Tested?

- local build with PR: quay.io/wenzhou/rhoai-operator-catalog:v2.14.910-0
  result similar to ODH PR
- mock build with passing env for workbenchimages: quay.io/wenzhou/rhoai-operator-catalog:v2.14.910-2
  enable workbench
  2 CM created + imagestream created: quay.io/modh/.... are used 
  see both notebook-controller and kf-notebook-controller have issue to pull image which passed from Operator => expected, params.env is working to use these images instead of one from quay.io
  

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Is this required for 2.13 release branch?

**Comment by zdtsw** [comment]
> Is this required for 2.13 release branch?

no, this is the original PR which is targeting for "main"
with both fix for jira 12409 and some misaligement of workbench in ODH and RHOAI.
i created a new jira to follow this https://issues.redhat.com/browse/RHOAIENG-12732

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
