### PR TITLE
[sync]: remove leader election for operator (#1000)

### PR DESCRIPTION
**Pull request by zdtsw**
https://github.com/opendatahub-io/opendatahub-operator/pull/1000

ref https://issues.redhat.com/browse/RHOAIENG-6798

and we need https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/2036 in after this PR is merged

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
/hold

Revisit removal of leader election

**Comment by VaishnaviHire** [comment]
https://github.com/opendatahub-io/opendatahub-operator/pull/1008

**Comment by zdtsw** [comment]
https://github.com/opendatahub-io/opendatahub-operator/pull/1008 has been cherry-picked to "main", should we get this one merged?

**Comment by zdtsw** [comment]
close this, we have re-anbled leader election in upstream, this PR is invalid

**Pull request closed without merging**
