### PR TITLE
Backport ModelRegistry Component

### PR DESCRIPTION
**Pull request by ykaliuta**
Jira: https://issues.redhat.com/browse/RHOAIENG-4272

* feat: Add ModelRegistry component (#775)

* fix: Fix modelregistry odh overlays path

* fix: fix dsc_create_test tests err nil check

* fix: refactor ModelRegistry.ReconcileComponent for new parameters

* chore: added modelregistry to README.md

* fix: add missing rbac rules for deploymentconfigs and daemonsets

* chore: code lint cleanup

* fix: added check for nil DevFlags in model-registry component

* fix: add nil check for dscispec.DevFlags in model-registry ReconcileComponent

* fix: remove RBAC rules for daemonsets and deploymentconfigs

* fix(chore): fix lint errors in dsc_deletion_test.go

(cherry picked from commit 112d3f14cbe54361d936582dcb44fbd71a69f862)
Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>

### CODE REVIEW

**Comment by ykaliuta** [comment]
Model Registry still needs to reach definition of done before we push this.

**Comment by VaishnaviHire** [comment]
This PR will also needto cherry-pick https://github.com/opendatahub-io/opendatahub-operator/pull/930

**Comment by zdtsw** [comment]
> This PR will also needto cherry-pick [opendatahub-io#930](https://github.com/opendatahub-io/opendatahub-operator/pull/930)

we will have a bit more work for the RHOAI namespace + some rbac part in ODH first

**Comment by ykaliuta** [comment]
@zdtsw was Model Registry monitoring rules PR somewhere around?

**Comment by zdtsw** [comment]
> @zdtsw was Model Registry monitoring rules PR somewhere around?

https://github.com/red-hat-data-services/rhods-operator/pull/318

**Comment by ykaliuta** [comment]
Probably requires to recreate the PR

**Comment by ykaliuta** [comment]
New one https://github.com/red-hat-data-services/rhods-operator/pull/329

**Pull request closed without merging**
