### PR TITLE
[sync] chore: change local "manifests" folder to match in-image path (#1143)

### PR DESCRIPTION
**Pull request by zdtsw**
- from odh-manifests to opt/manifests
- set default manifests path in CSV
- user can point to local manifests for debug
https://github.com/opendatahub-io/opendatahub-operator/pull/1143 ( https://github.com/opendatahub-io/opendatahub-operator/commit/5b7da9834f8cf5ce49609b6fbb0ecc6d5b329380)
- bring [705d980](https://github.com/red-hat-data-services/rhods-operator/commit/705d980f2dd729d801a61087716e0c0da587adc7) ("chore: keeps repositories in the tmp dir (https://github.com/opendatahub-io/opendatahub-operator/pull/774)")

## How Has This Been Tested?

local build: quay.io/wenzhou/rhods-operator:2.12.311

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ykaliuta** [comment]
It is actually also brings 705d980f2dd7 ("chore: keeps repositories in the tmp dir (#774)")

**Review by ykaliuta — APPROVED** [review]

**Comment by zdtsw** [comment]
> It is actually also brings [705d980](https://github.com/red-hat-data-services/rhods-operator/commit/705d980f2dd729d801a61087716e0c0da587adc7) ("chore: keeps repositories in the tmp dir ([opendatahub-io#774](https://github.com/opendatahub-io/opendatahub-operator/pull/774))")

correct. not sure why we did not sync that change in the past :shushing_face:

**Pull request merged**
